// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entities;

namespace tictax.api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220521101738_ActiveMatchesTracking")]
    partial class ActiveMatchesTracking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("entities.Model.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreationTime")
                        .HasColumnType("int");

                    b.Property<string>("OpponentUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OpponentUsername");

                    b.HasIndex("OwnerUsername");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("entities.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalLoses")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("entities.Model.Match", b =>
                {
                    b.HasOne("entities.Model.User", "Opponent")
                        .WithMany("OpponentMatches")
                        .HasForeignKey("OpponentUsername");

                    b.HasOne("entities.Model.User", "Owner")
                        .WithMany("OwnerMatches")
                        .HasForeignKey("OwnerUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opponent");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("entities.Model.User", b =>
                {
                    b.Navigation("OpponentMatches");

                    b.Navigation("OwnerMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
